In [8]:
import numpy as np

In [2]:
numpy.__version__

'1.25.2'

In [3]:
a=5

In [4]:
int_list = list(range(3))

In [5]:
int_list

[0, 1, 2]

In [6]:
str_list = [str(i) for i in int_list]

In [7]:
str_list

['0', '1', '2']

In [9]:
int_arr = np.array(int_list)

In [10]:
int_arr

array([0, 1, 2])

In [11]:
int_arr.ndim

1

In [12]:
arr_2d =np.zeros((3,5))

In [13]:
arr_2d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
arr_2d = np.ones((3,4))

In [16]:
arr_2d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])